// src/app/layout.tsx
import React from "react"; 
import { ApolloClientProvider } from "@/graphql-client/Provider";
import { ReduxProvider } from "@/app/store/ReduxProvider";
import LayoutRenderer from "@/components/templates/LayoutRenderer";
 
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { themeConfig, ThemeProvider } from '@/theme';

import type { Metadata } from 'next';
import '@/global.css';
import { SettingsProvider } from "@/components/settings";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <InitColorSchemeScript
          defaultMode={themeConfig.defaultMode}
          modeStorageKey={themeConfig.modeStorageKey}
          attribute={themeConfig.cssVariables.colorSchemeSelector}
        />
       
        <AppRouterCacheProvider options={{ key: 'css' }}>

        <SettingsProvider >
          <ThemeProvider
            defaultMode={themeConfig.defaultMode}
            modeStorageKey={themeConfig.modeStorageKey}
          >
            <ApolloClientProvider>
              <ReduxProvider>
                <LayoutRenderer>{children}</LayoutRenderer>
              </ReduxProvider>
            </ApolloClientProvider>

          </ThemeProvider>
          </SettingsProvider>
        </AppRouterCacheProvider> 
      </body>
    </html>
  );
}