import EmojiEventsIcon from "@mui/icons-material/EmojiEvents";
import CreateIcon from "@mui/icons-material/Create";
import PaletteIcon from "@mui/icons-material/Palette";

import {
  CompetitionStatusEnum,
  EnrollmentTypeEnum,
  SubmissionTypeEnum,
  ICompetition,
  RoundDetails,
} from "@/interfaces/competition";

export const competitions: ICompetition[] = [
  {
    id: "1",
    title:
      "Nature Photography Contest - Capture the Stunning Beauty of the Natural World",
    description: "Capture the beauty of nature in its purest form.",
    eligibility: "Open to all",
    startDate: new Date("2025-05-01"),
    endDate: new Date("2025-05-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-04-01"),
      endDate: new Date("2025-04-30"),
    },
    prizes: [
      {
        id: "1",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$5,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.FREE,
    price: 0,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.PHOTO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 5000,
    detailsHref: "/competition/1",
  },
  {
    id: "2",
    title:
      "Digital Art Challenge - Unleash Your Creativity Through Digital Masterpieces",
    description: "Unleash your creativity through digital masterpieces.",
    eligibility: "Open to all",
    startDate: new Date("2025-06-01"),
    endDate: new Date("2025-06-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-05-01"),
      endDate: new Date("2025-05-31"),
    },
    prizes: [
      {
        id: "2",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$3,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.PAID,
    price: 20,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.PHOTO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 3000,
    detailsHref: "/competition/2",
  },
  {
    id: "3",
    title:
      "Creative Writing Contest - Share Your Unique Stories with the World",
    description: "Share your unique stories with the world.",
    eligibility: "Open to all",
    startDate: new Date("2025-07-01"),
    endDate: new Date("2025-07-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-06-01"),
      endDate: new Date("2025-06-30"),
    },
    prizes: [
      {
        id: "3",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$2,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.FREE,
    price: 0,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.PHOTO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 2000,
    detailsHref: "/competition/3",
  },
  {
    id: "4",
    title:
      "Music Composition Contest - Compose and Showcase Your Musical Masterpiece",
    description: "Compose a masterpiece and showcase your talent.",
    eligibility: "Open to all",
    startDate: new Date("2025-08-01"),
    endDate: new Date("2025-08-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-07-01"),
      endDate: new Date("2025-07-31"),
    },
    prizes: [
      {
        id: "4",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$4,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.PAID,
    price: 30,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.VIDEO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 4000,
    detailsHref: "/competition/4",
  },
  {
    id: "5",
    title:
      "Short Film Festival - Create a Captivating Short Film That Inspires",
    description: "Create a captivating short film that inspires.",
    eligibility: "Open to all",
    startDate: new Date("2025-09-01"),
    endDate: new Date("2025-09-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-08-01"),
      endDate: new Date("2025-08-31"),
    },
    prizes: [
      {
        id: "5",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$6,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.PAID,
    price: 50,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.VIDEO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 6000,
    detailsHref: "/competition/5",
  },
  {
    id: "6",
    title: "Robotics Challenge - Showcase Your Innovative Robotics Creations",
    description: "Showcase your innovative robotics creations.",
    eligibility: "Open to all",
    startDate: new Date("2025-10-01"),
    endDate: new Date("2025-10-15"),
    enrollmentDeadline: {
      startDate: new Date("2025-09-01"),
      endDate: new Date("2025-09-30"),
    },
    prizes: [
      {
        id: "6",
        title: "First Prize",
        position: 1,
        totalAwardws: 1,
        rewards: "$7,000",
      },
    ],
    rounds: [],
    enrollmentType: EnrollmentTypeEnum.FREE,
    price: 0,
    mediaUrl: "/banner-back.jpg",
    submissionType: SubmissionTypeEnum.VIDEO,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    status: CompetitionStatusEnum.ACTIVE,
    totalPrizeMoney: 7000,
    detailsHref: "/competition/6",
  },
];

export const Featurecategories = [
  {
    id: 1,
    title: "Coding Challenges",
    icon: <EmojiEventsIcon fontSize="large" color="primary" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "85 Contests",
    participants: "150 Participants",
  },
  {
    id: 2,
    title: "Writing Contests",
    icon: <CreateIcon fontSize="large" color="secondary" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "95 Contests",
    participants: "111 Participants",
  },
  {
    id: 3,
    title: "Design Competitions",
    icon: <PaletteIcon fontSize="large" color="success" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "80 Contests",
    participants: "300 Participants",
  },
  {
    id: 4,
    title: "Math Contests",
    icon: <EmojiEventsIcon fontSize="large" color="primary" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "70 Contests",
    participants: "200 Participants",
  },
  {
    id: 5,
    title: "Design Competitions",
    icon: <PaletteIcon fontSize="large" color="success" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "80 Contests",
    participants: "20 Participants",
  },
  {
    id: 6,
    title: "Math Contests",
    icon: <EmojiEventsIcon fontSize="large" color="primary" />,
    description: "lorem ipsum dolor sit amet consectetur adipiscing elit",
    count: "70 Contests",
    participants: "100 Participants",
  },
];

export const RoundDetailsCardData: RoundDetails[] = [
  {
    id: 1,
    title: "Round 1 : Nature and Wildlife",
    description: "Capture the beauty of nature in its purest form.",
    status: "ended",
    message: "Ended at 17th March 2024",
  },
  {
    id: 2,
    title: "Round 2 : Urban Landscapes",
    description: "Explore the beauty of urban landscapes and architecture.",
    status: "ended",
    message: "Ended at 25th March 2024",
  },
  {
    id: 3,
    title: "Round 3 : Portrait Photography",
    description: "Capture the essence of human emotions and expressions.",
    status: "running",
    message: "Ends in 2 days",
  },
  {
    id: 4,
    title: "Round 4 : Macro Photography",
    description: "Discover the intricate details of the small world around us.",
    status: "upcoming",
    message: "Starts on 1st April 2024",
  },
];
